### ISSUE TITLE
sec: several things the verifier should check

### ISSUE THREAD

**Issue by diegokingston** [lambdaclass/lambdaworks_cairo_prover#110]
- Maximum degree of the polynomial
- Maximum size of the LDE
- That all query indexes are within the specified range
- Check the maximum degree for the last FRI polynomial
- Check the number of evaluations when deserializing the proof
- Check that number of evaluations and positions match
- Check the amount of zeros in the POW
- Check that all parameters are consistent with minimum security levels (blowup factor, minimum domain size, minimum number of queries, hash function, offset value)
- Check built-ins
- Handles errors when parsing the proof

**Comment by diegokingston** [comment]
For soundness error and security level, the verifier should check that:
1. The field is much larger than the lde domain. We should have that $|D|/|F| < 2^{-128}$. In the case of the StarkFieldPrime, this is obviously fulfilled. In the case of smaller fields, we should check that the field extension is sufficiently large.
2. The hash function has the required security level. For hash functions like SHA3, Blake2, Blake3, etc, with digest sizes of 256 bits, this is fulfilled. Typically, the security of hash functions is digest_size/2.
3. That the number of queries, grinding factor $\zeta$ (expressed in number of bits) and blowup factor $\beta$ satisfy the following inequality:
$\lambda \geq \zeta + R \times s -1$, where $\beta = 2^R$
If we need to use provable security, then we can use equation 5.20 from [EthStark](https://eprint.iacr.org/2021/582.pdf).
$\lambda \geq \zeta - s \log_2{\sqrt{1/\beta$} \times (1 + 1/2m}}$.

**Comment by MauroToscano** [comment]
Solved in [PR #130](https://github.com/lambdaclass/lambdaworks_cairo_prover/pull/130)
